/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevSseRouteImport } from './routes/dev.sse'
import { Route as ProjectIdReviewRouteImport } from './routes/project.$id.review'
import { Route as ProjectIdDiagramRouteImport } from './routes/project.$id.diagram'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSseRoute = DevSseRouteImport.update({
  id: '/dev/sse',
  path: '/dev/sse',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdReviewRoute = ProjectIdReviewRouteImport.update({
  id: '/project/$id/review',
  path: '/project/$id/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdDiagramRoute = ProjectIdDiagramRouteImport.update({
  id: '/project/$id/diagram',
  path: '/project/$id/diagram',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/dev/sse': typeof DevSseRoute
  '/project/$id/diagram': typeof ProjectIdDiagramRoute
  '/project/$id/review': typeof ProjectIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/dev/sse': typeof DevSseRoute
  '/project/$id/diagram': typeof ProjectIdDiagramRoute
  '/project/$id/review': typeof ProjectIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/dev/sse': typeof DevSseRoute
  '/project/$id/diagram': typeof ProjectIdDiagramRoute
  '/project/$id/review': typeof ProjectIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/dev/sse'
    | '/project/$id/diagram'
    | '/project/$id/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/dev/sse'
    | '/project/$id/diagram'
    | '/project/$id/review'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/dev/sse'
    | '/project/$id/diagram'
    | '/project/$id/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  DevSseRoute: typeof DevSseRoute
  ProjectIdDiagramRoute: typeof ProjectIdDiagramRoute
  ProjectIdReviewRoute: typeof ProjectIdReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/sse': {
      id: '/dev/sse'
      path: '/dev/sse'
      fullPath: '/dev/sse'
      preLoaderRoute: typeof DevSseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id/review': {
      id: '/project/$id/review'
      path: '/project/$id/review'
      fullPath: '/project/$id/review'
      preLoaderRoute: typeof ProjectIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id/diagram': {
      id: '/project/$id/diagram'
      path: '/project/$id/diagram'
      fullPath: '/project/$id/diagram'
      preLoaderRoute: typeof ProjectIdDiagramRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  DevSseRoute: DevSseRoute,
  ProjectIdDiagramRoute: ProjectIdDiagramRoute,
  ProjectIdReviewRoute: ProjectIdReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
